apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CzAdBgCbY/Y9H2ARYdyZ0VxN5ddB,iv:Z7bkVjuZQUvJLr521uv9MO2U0piSutG96Ni1ohZG5Mk=,tag:mIBtLWNeKL5IgKPVaxhswA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:aHtTJP8p8L+ZrPgokWATETkXVo1eq5QgrBdIkdor+zYrSnZmXQ==,iv:p2X8yFfIZml7nL3Stui6fOtngYa9WmiGFpwD3pcb29E=,tag:CphtjG6Ae4cSE4Q2qVMCHA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Zb5eVDmp8AwDQ4LU4hE=,iv:lrv7uBjjV2/9mNCe7aMV0yu/FepoH+LloTptMeDa2bA=,tag:rSJETKy3T9Ygx9GJ9B5uxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa0U3UGE4T24vM0JtZzJs
            UG1Lckt4RXUxcHJTanQ5Z1dSOEFXNjdJR1hFCms1Mk9YKzRDaHZFUXpUa0VzWFF3
            OEpDNlcvN1duMlNOOGZoeUt6YXJyK1UKLS0tIHdqcjB0K1lWekZPTjZEQXhWcUlL
            eGpYSGtUNzB0Q0s1QVZ4dTN6V1IrN00Kyc6IpIMlDtLhn9hi2iJzWvwPcMeeshhC
            YsQjQF+dOW3mG2FyS0rOZhpfSxbIwHovc+jmMqBIPRfmAufYq2JRGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-03T18:37:18Z"
    mac: ENC[AES256_GCM,data:rmvgdcVJedZMlDdoct1dnW9HPoN8AQd3m2TnMBaxeu9pWO6CV9eRyk3gbyh88a6EwZm5k1pDHf61RH5YdRAaOmRNBAx+RXUs1B9W7fD6LdGtsxqh1byDP5pZ3+L7qEmxgUOHVFOV63cQ1UsFUu22kk+flUG4CIeR8dVTAAS7vy0=,iv:CgYn9tRWqSjVsOfNcoIv6lAEc5s2tTlew27vylA/TSE=,tag:Q1KqxohsfZ4FzNXiJBaTBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
