apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qtDDussl4Z/JoSJpIQ4nDkuGCR5G,iv:eDl5CW2UV1giRdaroBHVR9BYYZ84g4xSIoBLVhTKn6s=,tag:sNxVEW0JamlR2g0dGTGWnA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:JxbdntWNB8uBv3Z0r+TUtRtHkm3ERRXXV1lwcpByrzsUpSQC7Q==,iv:x/C8zAu8A9KdhfQalIZVSU8eU6ms62K+TJ0pxnIa300=,tag:1IcGiPl2HcyrAjcN+nRRaw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:cO5yZ2JT8Xfv0jF6CR8=,iv:7U1GFWAq/79TA/6p3IGY+4xBaHHQkHcefJxWJZcsZMo=,tag:oELUvDPN/Kx6aq89UZ4M3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZDBnNk1yRjJEcVhjNkVI
            Y1Fxay9iOURFM1hPeXF4MkdxT21hanloM1NFCmlUTVpLTjVpbEwvQ29CYUtaTEVx
            bTBlTnVSQmMxaEFqcWpYMFp6U3Z5VkkKLS0tIDhXUjFmQ0k3NlBZUEQ4Tnc5V0Rv
            d0I1V1FKb0UrbjlldGluQmdZSVVsblEK85hoQE3HC09gmbauvwqPk9FIegX3VkRR
            Cu90ZU1LWCnU4+LTmCMDRXeW5uPNLCWCGV2eI07POdsbjKwHvCslqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T00:24:19Z"
    mac: ENC[AES256_GCM,data:bQIAhPer6AK91X0MkTPkfLy6zNx54CHsMce9HaCKQcoxxvNGm+N1wEZXfwqRLzqVhtYjp3wf1LlGL31+YspnXywoUajk3hQxz2RjBeA7AwFxXcdh2yx5oPfo5A98VdrSYN9OXl2rqjjqJScjX8XiENfo/TUAuIAaR9zyGfk+49s=,iv:9X23IRmd6aA3V52Pa+TjKBa1zDlfpbX0lVM5LIoL/LM=,tag:pyG7I/OEcjNmyLhcrxMIKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
