---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./tautulli/ks.yaml
  #- ./ombi/ks.yaml
  - ./overseerr/app/ks.yaml
  - ./invidious-server/ks.yaml
