kind: ENC[AES256_GCM,data:DI3weqvi,iv:8yYDG6xw7RUulHuT22U71mCGX8jh3Svemi/KGnO+umc=,tag:RVYy5diqo+ZrDuIVGU1SmA==,type:str]
ansible_user: ENC[AES256_GCM,data:XqIwKrYY,iv:QnuMlQkNCcoxpjmSS0j5gIFcLEwqZImzutqKNhcoScQ=,tag:PQO2FJwLoNAo0F6utwZPwA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:o7nS,iv:THPKnwCGvii0oKFxYu2ovlmvdlwGrVzQhSeHWCxMMF8=,tag:HRSlqWRzbh+2cdnwibvbmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aFdtR0Fwc1BFdTA2d3hS
            YWF4UFllb1dWV0E4UDMyMnhqM3ozcEZqZkhJCjM2MVJZRWhZeTZjWGxUYkFuYjcy
            aVBGcTZQV21QMU1mWlBOcWxmellHOVUKLS0tIG9FeW1nRmtUR3BwVWdtT2RPMGxh
            WXJOQUtlVHpicE9mR21mTCtlKzk2QUEKWsYEBpfCJxEvdi9sf6rITnDwwDYgUpv/
            5pSFdGfsNlJqUg160OQpVwSnJ3dC8EkQfOSsj7xm8323ep0ZcbWvkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T00:24:20Z"
    mac: ENC[AES256_GCM,data:+9/kzuuQj7L42MIRKMyMt23XSGlNK+mXrfkiSAlElFyaEXbjzlDP28Q7jiYmchO1ZaqCqOjo/G+ZJ1XVX3RVzgv/rNE/z1yd+f0a8EZxs9RvzDTOajWkjXm59Q7GVZDIim15GpEvhU7nanY81F2k1X2DzuL18qgrlZzJglW5q5Y=,iv:lo+aDiZWuRucii6V3b7R7nLwJ77OYVO0xuHWEazne+s=,tag:Y6gWS3ZPKxv9DfzE0IrOhQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
