kind: ENC[AES256_GCM,data:/oVPY9zO,iv:8w4vxeUtcgewzvGT29ueNDJHUguvsmambqaECzOAHDo=,tag:8LLeEA+gm8OrqvGfTkv2fA==,type:str]
ansible_user: ENC[AES256_GCM,data:eaAx5P1m,iv:6cGqEcLA0Tn5FxhFoL4uVdx9xnQ5MWX8uRZ0L0xBMLs=,tag:O2UI8l3orhhs3nTHHx4AZQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:w4Dm,iv:Iqe++rZ3CnIK62hn6Yd02Bm6tvdlBUNcRyE1Sh1GMg0=,tag:WTDi4xHAiVOLuXcoiCeM+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQS9kK1FhSVkvM05Lc3BH
            eXpBZytneHhOWFJ1Tmh2MlZSUFowRnRGMlJJCjYyV05WbEhlZ3RiVmxaQjhZc2g4
            YS9hSXFSYjlrdks5T1JqU0x6R29vOWMKLS0tIHRXb2NLcHQ0L0FreHd4eHRxT1F0
            WmFhWXM2U3ptcjVpWWdNRlBjeVhuY1kKlf1R7QO/ZV5Qj0ADnnLefMVqNFJgk2Uj
            wGx9rzBM8OHHNSbqQYtqSpD2rhlpIJPbOGcVk2skdE9Xgz4gAP4diw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T02:48:55Z"
    mac: ENC[AES256_GCM,data:bNzJT+vu+50Xo/c0y565AIyzSdRh7WlyAR0lsP7XQ1+DwrOLNJ2WnSwYoY+/jSAG0a3KnWULOLyOEYxp943syAwDPaIT3bhimbzLz7Fy9jpstWx4iVLz2x7bcS1ChhyxEcYvU+NFAj535/w0s+was7mNCJRmIpI2u+/vaXGM50g=,iv:Pw9Fw8hWvRM6zGE70KPLqtiGK4sQTvKsZS2R9ZA9N8w=,tag:F+nNO4BGNm2b3kfTmpqWug==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
