apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:WBTdIf1AVkufatIM1W1pq7KHEYG00Q/zhHK4I2XoD4+RqerirO//kQ==,iv:klCIplmwheCed1fMk+IWqFwlpiI8aM7U0rXT4a/Bc3s=,tag:vU/fOXMmmaGIq219uTZXiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVEJpV3hjTUJHRTczbDlK
            bFlRUzQyZndXc3ZGSE15QndXRzdKeDI1ZzFjCjhuZHkrNDA0WWxBQmhTbWJTeWFG
            VEw5b2R3T3Buc1FiQldkT3NreVlJTFkKLS0tIEhvb21UNDIrWUFpQnFXakR2U2lF
            bEw2anNLOGF1Q3R4ODJNTEV4aDVCRWsKYlTlubscmfPpvrUMQqrRXHVm/nooKdE8
            HyYi2UO2neHHLiilHNQ45hjgWzy7xz3hPJlNlPH5jQ2oVT/t9DinMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T00:05:29Z"
    mac: ENC[AES256_GCM,data:08c8UA4RdSi/MTp7UvO6zca9DRe1ZRUJRxiBIdwW2SWMtnO8Sh8yhmmzxWoPEY+Vs+QYTbVBVQwfEcURN5Cj0ZQSe9B/3ewnGJrivhCJOUiD/pVe0uynQmwMc7GVUZBleJR9S19z3xpfiNnaCMLCxUAlqap76MZJMRfKil+gMoM=,iv:pyBomGj5zICpCnLSVjQQxDpOzUzzxc05Q0S4QCDGZqQ=,tag:VU5yVXbvzLYRt1J6AV7NLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
