apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Pmr7Cd7W2B+jWOdn/9JHf+ZaHRqUPKsMzk3OWOQzgl3SjK9hY++ZoA==,iv:zRmluI7XFfpM1f4AYzMbuth0Qo418Q2nAlpgVs4hbkc=,tag:4bnpr86N9J8CbyZ8fRHsKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb2k1Ukx2alZJbXl0SXlW
            S29sM3R3NGNjSjg4WDdPUDZaNU1zaENVV2t3CmQ2MEtlMzg1NFRLek9YcVhxaGVD
            T2ZQYUdXWFU5Slg3S0djenlXUlNOTXcKLS0tIERVbzlVbzJ4MTRwVEl0bmx4MzMy
            NkJWMHF0TWpnZitaNU1XZGJsTDFPWTAKswoIt9pxUitHeCbvCk328YEgjRlEeOSz
            xqZc2OY2pvymGhlBp6hBapb+0TPM3pHxxPDSxRGMLcS9nVvVM9A8qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T00:24:20Z"
    mac: ENC[AES256_GCM,data:pB58kgg31WcS+7T/XuUQI7m9CzGMCD86NXXeimViGoav3Pb/U8P66H6f60Yasx6X9fpBNk8bG0uo8WgBSbbFB/2bZwNJoPYivyzHIl6KQ8gD5PlLWJx/6X9iu4EVsAAfn2BB5jQKKK21C55aVKOOzJkS8ynkGZmuiLGqdvEfJHU=,iv:PRS6uIVBd54RP+shSDyCZFTNMJau97Z5tp7TGX0M3iQ=,tag:ERst05D0YIpeuk07xEK4qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
