apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:ubngaJTqyxH6V1Qn/sQ+DYglL65E9YYjnJZkbgLOtuz7RtviOQ==,iv:M7WgRDEAMu5m1ObkZzzx/mpo+JHbAfOQ0ndK60QSxW4=,tag:Ou9+Y6l4HHck3AT0fCMLZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUTVMSUsrSWZHZ21COUQ0
            Mkt4Uysxb3dwWk8xOHRrRW0rcURUdzhvVUFZCkEyTHdsSUtncWE2ZTQxcDNKeWM4
            NnFlb1VjK3hKQmNmREtuMkZtRGdnRlUKLS0tIGFDTkpiWVhCVHNpMlVQVjd1Y3Iw
            Q0lXbGE1Nk5YM25kY0FpU0NrK3RncXMKaV5HeT7RSIiYv55gRipPJo8EM8lSpRI8
            2knD+ouRKuSh3o5hKewBvUWCmeeG81EfVyhRr8P6YDFRayaqf8grbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-21T00:31:27Z"
    mac: ENC[AES256_GCM,data:1t2HThkxv5+34rl5D1hIdV4zLL7sfDDOUDpQL9Gdum7D+FIzCbHJO0goSz3WDMlmR+b2n6JgocPoNfxslJDu5ljg9oF99phxckflztBu6hAozp5fXV810I7KCsaHYkKFZCWZjI/zz2hilwseGyz+aVflVxguWC+0AWgTsV1x3oU=,iv:ZtqRanYB0/7liEMpNd/lG6htX866TfxppVVCGJh0kes=,tag:RFV1R4iGpIb+yrhSdZVmHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
