---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/linuxserver/ombi
      tag: development@sha256:2ab06d413b16070e5301ba9ffb0273a553363462cc0efebaf6fe67b941e93ace

    env:
      TZ: America/Los_Angeles
      PUID: "1000"
      PGID: "1000"

    service:
      main:
        ports:
          http:
            port: 3579

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: &host "ombi.bhsnw.com"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: ombi-nfs
        mountPath: /config

    resources:
      requests:
        cpu: 5m
        memory: 200M
      limits:
        memory: 2000M
