---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi-nfs
spec:
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  storageClassName: ombi-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.30.9
    path: /mnt/zpool/k3s/ombi/
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-nfs
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ombi-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
