---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.471@sha256:67d6149e4537a7931259d02e131f43814d1fc9069ae46fb87896660f8674682a

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    env:
      RADARR__INSTANCE_NAME: Sonarr
      RADARR__PORT: &port 8989
      RADARR__APPLICATION_URL: "https://sonarr.bhsnw.com"
      RADARR__LOG_LEVEL: info
      #RADARR__API_KEY:
      #  valueFrom:
      #    secretKeyRef:
      #      name: radarr-secret
      #      key: api_key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hosts:
          - host: &host "sonarr.bhsnw.com"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config

      tv:
        enabled: true
        type: nfs
        server: 192.168.30.90
        path: "/mnt/user/Plex_Media/TV Shows"
        mountPath: /tv

      data:
        enabled: true
        type: nfs
        server: 192.168.30.90
        path: /mnt/user/deluge_data
        mountPath: /data


    resources:
      requests:
        cpu: 5m
        memory: 198M
      limits:
        memory: 198M
