apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:j+q3JC5TT86uX75epAZARQSUndhosfYgpP0Bfn2ceOWLcMp36ItXpI5Ue9DdR/4xwHatq3AZIXKEMB8V,iv:6RtkpmalUbMe8dZctLv3L+tSYr0zHjjJ0sH9PtDq8E4=,tag:KgqE66vTGvG0vKnnVfBYZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcGwranZZdTZlb1htWlp0
            M2J4dk14dmZaWlIzZTJKUjViYlQ5SEJuOHp3CitYZTIwZnl6VzlUSTFTem8xSjdT
            eTBUaFJwaGJYdnRvRTkwdytscXVzdEEKLS0tIElaUXNaYVBpRTVuR3llQU1KUkVY
            VS91ZEthTW5WMDNmSkdTN3dIci9pY2cKc7qCoRtmSA0GVkdBLV6AmknaxyMue3wx
            WMlnYdekDH3r+COC52lTET0jHHuS7+9xPPNYX7Uw7g92h1L3Fsutyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T18:25:11Z"
    mac: ENC[AES256_GCM,data:FBTRRTOstkUy50LYc6RXnzlVmiJXO+1SpW9YpBVc0anJcqM7rhpB/vlnaL1R+K69z1xuPf9jQUmvx1hRX1Is2kLZ7TixWNtA99EvPZC+SEu4exiX2blfOrkDGRb7C64g0pFFOctlSuzodaImGRs0ivDQzFWTAPaVoaKCeKx0ulU=,iv:VMwMSIoJU337WAHhQq80LV1UW+iDyhh3PrQmS4/h5Q8=,tag:HKHSAwo8SB5yv4jJ82tcQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
