apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:ii1vubmuGvGcM8iDcPQPogOt0aTHKPMEkP5ANbmYXI7YgUop+ej9a25Ws885Zi3FJdbnvEYfquQL91M+,iv:q9g08sDGv9hP2VO+Rt0CvZx4tq5335SqZ76N4jTcQKk=,tag:YK2uBd2dID6TA+YPZpelaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUDZYMVhVSnNxdFZ5TTFw
            NUwyL0FEMmhmWUJmSVpnNUlBcDJPOWNIbmg0ClZsSzBpbXdybm92QW9LdjFuTkR4
            S3hnTFN3MTBMY2thUGMxWXJnYXYyOTQKLS0tIEgzWmJhRUNCdjRJd3FGVXp4VWJM
            bHlETFczVERSZkNoZDNYdGIzQlFiZUEKe/kXm8bb+mB9bxXbz9pvU5XTgzai67+3
            XvaHPhmKsub8SfI4PF4G0hA6LT8kFAf11EG8vWQnoQFH4iiFYkmi/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-21T05:06:27Z"
    mac: ENC[AES256_GCM,data:wMFZLRAszu64Wi9fp4DirA+3JcFAvhUxcZhv4gb2WDcakxccYsFt/e5b8mXneLR13/fq3a1kcuiWlp8jitmII2WMecdZGMgiu1cMDkojiswkxpHblD1tEP9OEGF5DjZ9cCvSyXT/v6faUbbhYGJsNakQn9Nr6BDYGqBwsljIdVc=,iv:+m3iDKGmw0vAnKf0EECbNLCpoMubokF/GaQOXft82N4=,tag:+LhJsk9Y0CMqM9x6mdQTaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
