apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:lCHOODs98gIrRh5h06Y2RHMdB7WqW3Rwk3odVf3PzPjm6kD3cpe6wQ54v9KJG3IxTy69yVj4P8eqbxHC,iv:DZNh1CwAWpjOv38FgICgv9+tpedWLlmNkLsq5rKtbJ0=,tag:oQxdiWpPny8uX+qwXPdEPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZDRuakgxQTJHOG5Oc01s
            NlEvYlFzMEZBb3NkbWJkb3FHaW1xZTlVTWtRCld3M2IwMXNoRy9MaVF0QUtsbUs2
            bTk3bVpEb296WXFYSDEySXNKSzdiTjQKLS0tIE5kNHdUcWN0SVdhZWRHVnJnWDBt
            TnNocXdNVGt1c2RVbi82R01aeU42aVkKzQaHbM6PHW4An6HikFjWpvLtjhy43VsO
            mmsrYt2nI+sjCdJ/UO9TrGfM/ncBmqKoW2gwWoogUwhJWfqbSUxomA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T02:48:55Z"
    mac: ENC[AES256_GCM,data:kdHUsBAmtA5YQ2iNyUEyqpuaEVEKd7RMu9vW/ZOjAh6dd8Ndu/R4yjZXyFBOLAJd2cKSOamm/l/wfS62ovv/+GXuVatYXBPrsaClTTXmR5gCkE77w1svwfLdzMN5Cx/jPZpfs3kQhlqUZwCZKgToGoumjZFOCYNL6oTplt7KsDo=,iv:fjzgbzuSLcOkqGS7ouE7+hRK5ScFCz7mStEttFwSFXg=,tag:fXsufg87APxQf9VLBQkRpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
