apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:qqMndzNtULCWcXWxSruS3h3I+JvgFokEjRs6gjNbwL+g8YYjXpDhaM70g6ZH/IjTeMUWBaHzw3nSBO+z,iv:i1iMbwG3beoaEnZU/MYKCpp9k4wpRoipuYSOmeXz0LE=,tag:X/qu7+RETI2rpANTHC7mjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ3FXVmdXR0luekluLy9D
            cjZvT21MWUhsUE52aW5lNDRxaE5hRFdlTTNJCkVlRGVPMC8rNEsyN2lpVlhONVBQ
            bDJZbGVmdGx0QWdPQlNFVXZNcEY1SVEKLS0tIERoWnNiK1hsSnpLMER1djJMU3VR
            d0hmazg1VU9hb1JweU1FeTV2cGNCdjgKK+SdoP4FzYt4uhrDaUb88Q+JK2jKCEq6
            3xOkkTw101EplYEN8rIHuLcE1wSm9yJvE9DlApU9hJIZQMSG+blnSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T00:05:29Z"
    mac: ENC[AES256_GCM,data:drR/8xolFrKWiMLCzCYRJ4KXCOW/WeB22oL91sFOmg9ziTSnzGVgp+hCUodu2O1PC6NCQZMvBIt7GKbHmfxe9JS0jb8fQJp1Y8+LvnirK46Y/UJ3/Hm6DuEc4VNfZ5inpZ8IMMkMxqM12/fAhkwr+aZoKkwhnbjVe5S73yudFpI=,iv:Yt0SAXtyjo7lurD3xPaoyMcfHpiF1l/YUzLsuBrC99I=,tag:BzOZjtlKL8XvUuLMMSD8cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
