apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:JscH50K0yWwBADiKcXZrrE9eD/UUIC6W2o9Xpe0mF2qBc40pzkiSDy2fx7jmMiJIYqNPWz6bxf3gmKW/,iv:8W1bT2ICo5MVJvosGTy8E4SKRewBoJfiS/fM7ZyNImw=,tag:CBFNvNnkOVr+8Wd0B/9ghw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOGQ0bmt5dktERElMSnNL
            RDZiUStGV1FYdXNrQjByNkRXZnpEbXNyam1JCi9WRUZ3cUkwUWJ1bkJwTGVKVTFD
            K0xBb0FXWkVlNFhZUGRoeGw5NG1aUE0KLS0tIEJodFBGZHdqTXJzVkRuMjZDYi9t
            V1g5UUVpUCs1QjlaTEFTVXVxSXdVK1kKgzwiIXQwBMXZAtw6EHVwyeanY0NJMumN
            4Pbx8hk3OwQ1qlf08hmEbvWIWveoo60VUZrW8sLhKstrQzv1pzMDTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-03T18:37:19Z"
    mac: ENC[AES256_GCM,data:za2jVIwb4bywC30Aa2IxsYzGJZpafbBoMkPiUZuCV4wKiIWSlCUOHBCtqqhO8tpCfRXzigATa/33VXc3UhflWomCSCGIobwH/oMJSM5PWyqMgzmpjNuWR23EtQ4c6dfA1G5pY9FyNOiHWnC0MpNOQBoRyUX29GanBgxIoHzkhaE=,iv:TGlyhZuJkRRy79yC+ds7YGcmmeI9rCDwYNyAahTzIrw=,tag:xhMVyU6Y4LaYWEC+EEP16g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
