apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:vNXUiJ9tPI0nl6PWII6vnF9OjjRNtrKxjEBaY4mdJwBKujn7hkBYwlRop/zCRb/Teec2b9K3E9wsT+rD,iv:qTJa/BB6MLh3RCIiWyeBlodxwgjJqz+hNKdYB6OcTUw=,tag:Pq65jKl17zFKJhviSBjBMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0T3lUeGJnU293N0RtakZM
            VnJVdEZ4aFo4YlF0eDY0Y2VnYzd5bXNWVGw0CmFzcHJiSU9lM1ZaUE5rTzlUaFRl
            bmdPSWVIVFlkSHM0bGM1cFdJa0xqOG8KLS0tIEtsamZVRGJXRGR0VTlnQTV6Y2JM
            ZFRuYnptTDdkR3FIcmwxMGVIWHFabE0KHkwwKa0Y1ZqnXby3EsuE5+hiqeXIkzRV
            kaOJU5givljyV4U+Qtg0w2oSQs4V9I54TGqPKSfszaqICd1PeOXoQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T00:24:20Z"
    mac: ENC[AES256_GCM,data:JEIBXueqXbE8BhuFmLv+Zs8nO1V+3FRKspmYjcHXVtOzu6qVZ943j/uO3sbYBBb93N9zy9cjM4+wwyiIue5JR+hQmi0KNCwoJbNuDphGwud4vZ2XNdnkpgrTHhesT7blfnhVa4X5fBXjF5N4D04wDJqOeEO3dcN4wREwdNQxQhg=,iv:Kcsx8gqPuglaqa81kdqw0q2clE7xYq5kypMDVolcQCw=,tag:dPhsFuLBISOt0LHqOaQQBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
