apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:5sh1OpK6SmnUfDwmqfaU/CRvPaV9fAKsBoa6BCPITfzxd8a3JcHLiL7kkcLt1Dl1NF/ElgUBBqxTLxDT,iv:ZZHvARivqVwInMK1SqsB+5uBRtxKgPYh1k7TLpF7bf8=,tag:/peEL9lYQxkY1GNL7D2Vag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdEF6WWpnVDNEcXh3OXhZ
            ak1aejhHYTZPY2EreDA3QWVDSHZCTjQ0NzBVCkpxRmtGVXQyYTF3RzJSSFRiaUZ4
            ZEZXSCtMZjRWZUd0M2lVN1dyVGJ5YTQKLS0tIG42UFhvTUQzRmtJc2EvNkJ6WEY2
            cHNqSXJvNFNmN1BIaXhQVmluRjJxQ28KQIzZE9xzLiN9QTjzDtx9UpFHHD0hRGS/
            J7USweXEA1NWFvrriQ6ABvHnaR4oOaD9CsT1CYPFSoTL1ClnTFDbGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-21T00:31:27Z"
    mac: ENC[AES256_GCM,data:vijADda0+pI8KMcYDdCGgATb1Id6aQC0MSLlfnyBtb5D7246FK//co2r58Or/V2tN0yhscEYimRqzpSsOmgY4b++u6AC5I9M4O+kglUd3R0+6wZvRECWtwaA7N1q+ktLZBuC+wZJ2bexq7aljiSmpIvp+EbVbPrUtvcfT7u5qic=,iv:NwG65t9VrRHmNtxn4DoDwWrIsyaGzxjbBsVRWmmIp1I=,tag:DwAv7A3ur5hrv+KQbROweQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
