apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dWzqAYIvqFBI,iv:IWhebDjyrXiQ1mrz5TO8kqTetjD8+fRhmeQ0aBU5mdQ=,tag:2d4jY7MKnGq7yuGG+aegCA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:FwwdJGtFldVPrltrZipGFhluIf8T,iv:Y48elVZRG6Q1gAHtlUxwzghYZsqGCqQweNnu/v0oJjg=,tag:PObJqujQFcJZ9yvBuWNdnQ==,type:str]
    SECRET_CLOUDFLARE_ACCOUNTTAG: ENC[AES256_GCM,data:+NTytc4lciMSudDJ,iv:6SOdrh/5NRtByi5kQlkLTbJemnEEUawtKv3dZrD3jWE=,tag:nTr/hUSuQLZUvvVzgrsmSA==,type:str]
    SECRET_CLOUDFLARE_TUNNELSECRET: null
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yCwHiL5BG/sY13vDbrIvFlav4F1ljT+zAyQns1hr1aJrbwU1,iv:z6+B7WUM1U3XYyQRqcP0LN/aucMp6KGD0At9PA4FLG8=,tag:QqaFROKEc86GAZNfikJQJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZmdYcGh4eUU3M1hIV082
            dXRkUGQ5Z2dNTVg4VU52bEpKckRjVTg0dVNJClY3NnozTFgwZFFSdUk0ZzZZeGVN
            anJKSEJuRmhNaXFhSzNMUk5mSlU5ZEUKLS0tIG1jN2djV3ZPZUhVTFRnbVVCendu
            UFBTOXdqVTVVSENvY05renByQUhSL0UKEHVmRP1w3UG7ye8Bh0npx2UtfSjy6vnv
            nozbwdPmB6zfHxfskUbKiqGZBHW3hV9ZIwZDdbAmyMofOW56rYOJ6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-31T04:47:52Z"
    mac: ENC[AES256_GCM,data:4HqZ1N4em2n89UFcyvTLYBVrcoWIEeAOf452XYT4rkcJTDeCNjMcRztnYyWfrpaK7/ywUeeAg+/n+r6/JFUIeF62Iamv5EClwH+YgOAGzzoy+JgaBIh8Tw36xXgE6NJl/uK93+Zgs/mgeJFm0dLu4G3DSci7gfP1O12RjOcFJSw=,iv:8h1Hw9PtA/788mCLCtcqHlUXvOgFzaeplRDBS9Z8ODc=,tag:KKVmHxFJgMTe040q6MD6ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
