apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2eee9kOOplIu,iv:aOQt8srZ9eRXXyz4npOVol+6l7S003q0YKfpy/3t3QM=,tag:wLUMBartCC6QzGdq2se1zQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:XiPTqdlgClWih2TD7VVqwZvgaDZa,iv:wx4MzDUvPyeYX6Zq37thOzoezhREPJDUKlA6Fp1ISE8=,tag:IQM+c56biLwDN7nfFkethg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb2ZkOWo2NTRDODNoSDFN
            a0dFWEx2NHBTNXlKdGRkSlFwcmNESGcyT2pVClRDVE1zS2EzS0lwK3VvcE11a3Ux
            OFBYc0JwZ2JtMFhEaGpnQlpZam1SZVkKLS0tIHMxQ3M1RktrZ3JncFdjSnVJNjly
            QXJQeEZDQlNhVGhNUlBFdGF6V2lKb0UK8+NNkFc+xT5+tbP49Ve9UdlwoFJsOjM3
            /09GDc/J9x+C3MMPu2AZEQuZnNMo8x+FMkodSBtMXMLVFaDCa82tcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-21T00:31:27Z"
    mac: ENC[AES256_GCM,data:YAZWdPmPH1NLYUnkKqkxri20amBnqhly45yPmbhCCRQYTb3ymkKEI51sQFeI04Rf40UxqM6NJQBnvB/RNDqfKspWlVUZxs8vZycnqUfBszV7nC7Krd+Cz5+NkXkBT4IX1Sps3J/KJBVMIxtrYJqrgaEQ8vgyNEUZwqNJWo7QhIg=,iv:DpnYsPbwPtcfeozJiOkYNajatMrfxLim2bHQv1FhBHg=,tag:ZlUe5KMsFZOk7F34v5X0ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
