apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hM+yquG4ITsq,iv:TQEbuf9D7OW9KwirYVfGxlI3BRY/5dU39PpzkmO19sI=,tag:zYE4YD7Ex+cmRLIDyXubew==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rXeGQgwLgsCa7Usg50UryZmK2c/G,iv:JnpvsRdslPvxFpUBwZ/+jAQzy3W06SqHiFZeQRegXP0=,tag:fkqbyYk507GJusfp/k1Qkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OGw1M1Uzd2thM1p3VXdx
            MVVLMVVOTm9DNE5EYVZMRVVYaTUvZk1pV1JRCjNpQUNIZkQzSnBMdWJ1dlh1OW9n
            T2VYNXJkU2MzMFZ4Mjd0RUVwTm95cUEKLS0tIFdaQkRzQU1rd3JLZmNpWm9pV0dr
            VzBPYWRrem16SWhxNGF5Q2l5NE1tSE0KmZ/hXmJNRX0TlC3HI0zNROk3+qohnWYh
            TBCbD05r9TDmUqD1+gy4G3GxcNOa+agxGdi1B41pCIUZNz8ARZYH+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-27T00:24:19Z"
    mac: ENC[AES256_GCM,data:SBCgPyW2QLcEUoQ+e49+cP3Tj+9MV/8FzrhgRIBvq5jRwyszcQbs02sKZKcKzJcF0y82AX/uB91qgY/n8UrFyrfEj+Qn/aXu6/KOBANeoAANHOC9VKx5GItpNbUKp3pHfHsLw5BR7ttAyoP4GVZZKyDGH0XGzCO5gx/ZRZ3U16U=,iv:wUaUJRWyisI11y/kbBT8wIPP+k4n3EAPeq6lD5bDxys=,tag:00R0iJFyDCa6eD0Krj8aAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
