---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "192.168.30.59"
  METALLB_LB_RANGE: "192.168.30.60-192.168.30.70"
  METALLB_K8S_GATEWAY_ADDR: "192.168.30.60"
  METALLB_INGRESS_ADDR: "192.168.30.61"
