apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:nbJLHVBWACUR,iv:m4INgU36iIs0R80vDQNiziEhcLcHIDohou4unhdBSWc=,tag:SXmRkM53KSC6Pem7zzkmLw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ovPz73Wx4rV8MPujXfjBjKP573Wl,iv:8OO37mSsZRqtosovoTKhHeqRcpPYTjrTBoW7OpeHDE4=,tag:WvOEJjMhF29LwG/Z1jxWjw==,type:str]
    SECRET_POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:Bq3CdtGQbqELRsN2,iv:hpytmK3V/m8FF2YZU4PKreBPdMDSd5Kb/KJD2FKdBGY=,tag:tNRyyn2zCYnCCYLD8O2Rsg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TPH4ciS4bzioHaWseLc01OJ2suPmyqSE63W43PtoV3wBNKQd,iv:h25BPoKNljQmaQ7e7MUzOTPm/hpMZVJfqV/6makS2VI=,tag:8t6SEfYXlMCwhSDPDIY46A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSHpsVWpiLzVQeG9RbS90
            N3FKdGNuRUxNU3VGZis3WlpGUVNoWUJ0Rkc0CnFWZUhxRURSUER6WXhTVVBrL0lN
            U3llZTVmQUp3dVI3M3loSnNQS0ZSeFUKLS0tIFhXK2NlMVdaamllakJyRjFkWXNG
            YldsSUZBV1Z2bmtBWjNUNmRYUXVxM00KhixM61QuPH0s1osxN/hZFSvOYB7HQULh
            40hjNPFC0ncSDHAlWLERPsA2NvdyRpEq+qbuIkWgZGJAlwX5e8jG+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T08:27:26Z"
    mac: ENC[AES256_GCM,data:lhKim+iSmeFjP9BXTLrlJGkitZGWlf/gKsOUMacCZsbRYhyS+xdJkMZ1nuSYQrGTe6tL4WuS8gGboCAgbs32qCo0gG9851ihtEIaBzN2ZvLb0SBPRFaQae9DWGKwNk3fAB2nRgd6S9UzDoVj6IccKKhDHSi+rTiynCbfL+kTcgQ=,iv:0NAxHXhlWgkvQHAwPm7EGf6YlWDpYhyOpOXfltfhQEI=,tag:+CTQwE0Vw/sAotQbc5tP5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
