---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudflared-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
