---
tunnel: ${SECRET_CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/cred.json
originRequest:
  connectTimeout: 30s
warp-routing:
  enabled: true

ingress:
  - service: https://ingress-nginx-controller.networking.svc.cluster.local
    originRequest:
      noTLSVerify: true
