---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controller:
      replicas: 2
    image:
      repository: cloudflare/cloudflared
      tag: 2023.5.0-arm64
    args:
      - tunnel
      - --config
      - /etc/cloudflared/config.yaml
      - --metrics
      - 0.0.0.0:9090
      - run
    service:
      main:
        nameOverride: metrics
        ports:
          http:
            port: 9090
    persistence:
      config:
        enabled: true
        type: custom
        volumeSpec:
          configMap:
            name: &config cloudflare-tunnel
        subPath:
          - path: config.yaml
            mountPath: /etc/cloudflared/config.yaml
            readOnly: true
      credentials:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: &secret tunnel-credentials
        subPath:
          - path: credentials.json
            mountPath: /etc/cloudflared/credentials.json
            readOnly: true
    resources:
      requests:
        memory: 64Mi
        cpu: 10m
      limits:
        memory: 128Mi
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
      configmap.reloader.stakater.com/reload: *config
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - cloudflared
              topologyKey: kubernetes.io/hostname
