# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: networking
stringData:
    cred.json:
        AccountTag: ${SECRET_CLOUDFLARE_ACCOUNTTAG}
        TunnelSecret: ${SECRET_CLOUDFLARE_TUNNELSECRET}
        TunnelID: ${SECRET_CLOUDFLARE_TUNNEL_ID}
