# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: networking
stringData:
    cred.json:
        AccountTag: ENC[AES256_GCM,data:3mG6dohGWfI5wDEUk/r15prV5RIcFr1qWeLthUmjgnk=,iv:YFhjxXhfuZ9x6NbGIwXUdCXYPzE7pPlEH2zqLFkU/Gk=,tag:rEI0dhjpa/4jXUxU0yOu/A==,type:str]
        TunnelSecret: ENC[AES256_GCM,data:VEiClx9SjQ3Srteo+YW+b421p8M9/F+WBeYN9ZN/mcHWYkIreX0ynMYRBCs=,iv:OCLDgjgjq1/KFSMXktC+Pex7g5ZqiOCIquKX5NE2mk4=,tag:dX9D46hxgTVx/OqEOp9r/g==,type:str]
        TunnelID: ENC[AES256_GCM,data:Ranqk7UGKK7iXROKyg9V/I8QefbmI/Z+J8XMk4tDTijJKyfT,iv:XAZkz0EGEToSM2FMU7W7ExLi297qdKf0zv+k+5pevvA=,tag:t3vArv36XcNwYS/rq6zGBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdHpKZTlaUmExeC80Mkc0
            am5lMTVoTXFpdC9kR1BoZnkvdnFVaFBYczIwCkc2endna0J2RndVRE9FbW9OZVBK
            MUM1YXJJNGozejNNTStOeWcvempPbU0KLS0tIHllbDQ4S2dTUDZPK0xuaXJJRVBD
            UVhwVEVycmZpaGtKbjRMalY1VjcyLzgKSpdQZcrnWW2UElzQXipH0YKE2zT/ZQA4
            XgaCleoLypPWM7yZ7l692t8zndArJkY1ZuoTH4wTwumIAUrnP3ZXrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T08:55:11Z"
    mac: ENC[AES256_GCM,data:6ewmY98FLnQR44r0m6tn45C3zVylPMgHK75QiSYiySLg4nQHySKuzsgrUBunZcQ+XqK3XgFTEKOIwXkCV/XknO5JzS2qE+OviMGIPEEmNudQzxd1kw5I6xgfmYHrUInWni4ueJ4JzYRTgK8FnGOGHLj1R6T2OCkK93weNnsimlY=,iv:WiQgQjHMZLzZY/N7XBDBKvKixPhzZpNYtL7Qo8fagX0=,tag:j+NS572jfGojgPVtBVIDjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
