# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: networking
stringData:
    cred.json:
        AccountTag: ENC[AES256_GCM,data:8xBWtk4Ie7FIIfGpWYoBUbKuXfHdYIR/+mbg7zzqQA==,iv:1RGtP+17uxfcChQdOwtsgZs2v5HrlivWn/Piy/26W8A=,tag:5hF1OEBULtjbFrxBm86wSw==,type:str]
        TunnelSecret: ENC[AES256_GCM,data:YjqueenA3Qn+CAZgGuyOBeFzciU4+NkN5wSngJBBoZ3I,iv:U8idYmFHWJDc4E9FHKpW+22JIbFj3MSHSMi2flTUK7o=,tag:z3FMWQPxCe1LJY7WJhF4jQ==,type:str]
        TunnelID: ENC[AES256_GCM,data:muqyjvPcLHtw6PtNzjtIZXqVpswaHVhbKNHy6S7k,iv:fZVag8cb9CWPaTNBv66PUqFUJy0Wvtx6AoU5EYnyV5I=,tag:iiozLORKnu/UkjxoP7vRKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cayn30qj20nwwvw3f3xgsy4u0sqym72wty0ykzvqnyced33w5s2sl5zj39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWU5PWm5IS1NwRWZIdU13
            UHhWTWVxV1R2cStCZFlPL0hGMHZFRUYxelZNCk9Yd1cyYlMzQ04ram9NL2pQN2NW
            dTlOU21ScXJJdHAwSEZQZERiejgvOUEKLS0tIDFsTDR3Y1dnbzNybG5heXJrOHNm
            Qk93U3A3TDkxQTVwY0l4SHIxRW5saFkKkkUvWH1QcAC7Mo9PjBxwLcWZTXIKJVbY
            tl881Sp6YePWhri1aAxz6ifb2Y4WTdvi1Sdlb5ybJe/f+IkB+ViEcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T09:03:58Z"
    mac: ENC[AES256_GCM,data:LyBNkC74fCjLQHDTQ3gCSm8KL4qlV2uxhkn76VE0hDlu7gk1evjOVUuPvVzR1phe+wC8GbfostV1atcZhn/mahzNTiZT+Pg2d+q6xZr32UlqjBlDrDuSZ4lV+WgrkWpLTsVIWcc/Q6EgODvdfbm4cmEo2fOyPQGmxUf8R1XMaLg=,iv:qm446RSy5x6nhfTwRKNb+LEAaOmv3yewuYJbNFhKM0U=,tag:lXXEAPnN+6d65Dv1fUTqrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
